### ISSUE TITLE
Index assets

### ISSUE THREAD

**Issue by vikiival** [vikiival/unique#11]
In `schema.graphql` define new AssetEntity with some params (inspire from hydra/statemine-assets)

```graphql
type AssetEntity @entity {
  id: ID!
  name: String
  symbol: String
  freezer: String
  decimal: Int
  owner: String!
  admin: String
  issuer: String
  creator: String
  minBalance: BigInt
  totalSupply: BigInt
  burned: Boolean!
  frozen: Boolean!
  blockNumber: BigInt @index
  metadata: String #not sure
}
```

in project.yml

```yml
      - handler: handleAsset
        kind: substrate/EventHandler
        filter:
          module: assets
```

In `mappings.ts`
define (it should be similar to handleEventMaster)
```ts
export async function handleAsset(event: SubstrateEvent): Promise<void> {}
```

Do not forget to change your starting block in `project.yml`. If you are not sure check [Statescan](https://westmint.statescan.io/)

[All events are defined in the pallet](https://github.com/paritytech/substrate/blob/32a4fe01f110a755bf22eb8f803cdfd7052d4f8b/frame/assets/src/lib.rs#L384)
